name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
  - name: Flutter action
    uses: subosito/flutter-action@v2.6.2

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get packages
      run: flutter pub get

    - name: Test
      run: flutter test --coverage

    - name: Build - APK
      run: flutter build apk


    - name: Collect the code coverage
      uses: testapp/testapp-action@v1.0.3
      with:
        token: ${{secrets.COE454}}
        coverage-files: ./coverage/lcov.info


